---
# Full path to swap file
swap_file_path: '/swapfile'

# "present" creates the swap file, "absent" removes it
swap_file_state: 'present'

# Size in human readable form as is understood by filter "human_to_bytes"
# eg: 1G, 1M. Defaults to G
swap_file_size: '1G'

# Priority for the swap file. "Higher values indicate higher priority".
swap_file_priority: -1

# Choose between using fallocate and dd to create the swap file.
# On btrfs the default is to use the btrfs command. If you choose
# dd or fallocate when creating a swap file on btrfs, you will
# also need to have the chattr utility installed
swap_file_create_cmd: '{{ omit }}'
